### ISSUE TITLE
Version 3.3.0 fails with "Error: Installation failed: Destination file path /home/runner/work/_temp already exists and" (at least Linux, macOS)

### ISSUE THREAD

**Issue by michaliskambi** [gcarreno/setup-lazarus#31]
Upgrading action to the 3.3.0 version (from 3.2.17) causes errors when building at least on Linux (reproduced on `ubuntu-latest` and `ubuntu-22.04` GH-hosted runners) and macOS (reproduced on `macos-12` GH-hosted runner).

The log shows 

```
Run gcarreno/setup-lazarus@v3.3.0
Starting the installation process.
Installing Lazarus IDE
Lazarus installation completed.
Installing Additional Packages
  Packages to install: 
  Requested Lazarus packages: 
  Fetching package list from https://packages.lazarus-ide.org/packagelist.json
  Fetched 206 package items.
  Installing packages: 
  Downloading https://packages.lazarus-ide.org/ to /Users/runner/work/_temp
  Destination file path /Users/runner/work/_temp already exists
  Waiting 10 seconds before trying again
  Destination file path /Users/runner/work/_temp already exists
  Waiting 11 seconds before trying again
  Error: Installation failed: Destination file path /Users/runner/work/_temp already exists
  Error: Installation process failed: Destination file path /Users/runner/work/_temp already exists
  Error: Destination file path /Users/runner/work/_temp already exists
```  

(for Linux; for macOS, the log is similar, but with `/Users/runner/work/_temp` path).

I can reproduce the issue with the simple workflow, just using `lazarus-version: stable`, 

```
name: Build

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install FPC+Lazarus
        uses: gcarreno/setup-lazarus@v3.3.0
        with:
          lazarus-version: stable
```

See https://github.com/michaliskambi/test-setup-lazarus -- feel free to fork it and experiment. The build YAML is in https://github.com/michaliskambi/test-setup-lazarus/blob/master/.github/workflows/build.yml .

**Comment by michaliskambi** [comment]
Pinging @vmaskmovps about this :) 

( I hope it is OK that I ping you about this, I know from recent issues that you're actively developing this GitHub Action, and you did release 3.3.0. Let me know if you receive notifications about these issues and I should be patient and not ping you :) Thank you for your work! )

**Comment by vmaskmovps** [comment]
> Pinging @vmaskmovps about this :)
> 
> ( I hope it is OK that I ping you about this, I know from recent issues that you're actively developing this GitHub Action, and you did release 3.3.0. Let me know if you receive notifications about these issues and I should be patient and not ping you :) Thank you for your work! )

I do get notifications, I just slept earlier than I should because of debugging this issue (it's currently 6:40 AM here!). I tried modifying your build.yml to this:
```yml
name: Build

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install FPC+Lazarus
        uses: gcarreno/setup-lazarus@fix/temp-already-exists
        with:
          lazarus-version: stable
          include-packages: "Synapse 40.1"
```
and it doesn't show me that error. It seems it's only a problem with no included packages (aka an empty `include-packages`, which also triggers this issue). I should perhaps short circuit everything if there are no packages. I'm inspecting if this issue also happens in v3.2.17 right now.
