### ISSUE TITLE
Installation fails with `E: Unsupported file /home/runner/work/_temp/installers/fpcsrc.deb given on commandline`

### ISSUE THREAD

**Issue by JanEricNitschke** [gcarreno/setup-lazarus#32]
I have been using this action for a bit with:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Lazarus/Pascal
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "stable"
          with-cache: true
```

And now have started to get an error when the default seems to have switched to version 3.6:

Now failing run: https://github.com/JanEricNitschke/TicTacToe/actions/runs/11872719239/job/33086747588#step:3:1
Last working one without any changes on my side: https://github.com/JanEricNitschke/TicTacToe/actions/runs/11791730905/job/32844242358#step:3:7
